name = "pharaon-server"
main = "src/index.ts"
compatibility_date = "2025-10-08"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CounterRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PharaonRoom"]

[durable_objects]
bindings = [
  { name = "PHARAON_ROOM", class_name = "PharaonRoom" }
]
